  // IMAGINI NOI – GALERIE REALĂ ELEMENTAR
  {
    id: "3-color-chess",
    type: "image",
    src: "/images/3-color-cheess.webp",
    category: "Iluzii Optice",
    title: "Șah tridimensional cu trei culori",
    alt: "Instalație de șah tridimensional cu trei culori pentru dezvoltarea gândirii logice la ELEMENTAR.",
  },
  {
    id: "catch-it",
    type: "image",
    src: "/images/catch-it.webp",
    category: "Experimente Practice",
    title: "Joc interactiv Catch It",
    alt: "Copii jucând Catch It – joc de reacție și coordonare la ELEMENTAR.",
  },
  {
    id: "group-children",
    type: "image",
    src: "/images/crup-din-3-copii.jpg",
    category: "Explorare",
    title: "Grup de copii la ELEMENTAR",
    alt: "Trei copii explorând instalațiile interactive din parcul educațional ELEMENTAR.",
  },
  {
    id: "cubes-real",
    type: "image",
    src: "/images/cubes.jpg",
    category: "Experimente Practice",
    title: "Cuburi interactive de construcție",
    alt: "Copii construind structuri cu cuburi interactive la ELEMENTAR.",
  },
  {
    id: "elementar-selfie",
    type: "image",
    src: "/images/Elementar-selfie.webp",
    category: "Explorare",
    title: "Selfie la ELEMENTAR",
    alt: "Vizitatori făcând selfie în zona foto ELEMENTAR.",
  },
  {
    id: "organe-interne",
    type: "image",
    src: "/images/organe-interne.webp",
    category: "Experimente Practice",
    title: "Organe interne – puzzle educațional",
    alt: "Puzzle educațional cu organele interne ale corpului uman la ELEMENTAR.",
  },
  {
    id: "pentagon",
    type: "image",
    src: "/images/pentagon.webp",
    category: "Iluzii Optice",
    title: "Iluzie optică – Pentagon",
    alt: "Iluzie optică geometrică de tip pentagon la ELEMENTAR.",
  },
  {
    id: "real-and-copy",
    type: "image",
    src: "/images/real-and-copy.webp",
    category: "Iluzii Optice",
    title: "Real sau copie?",
    alt: "Instalație educațională care provoacă percepția dintre real și copie la ELEMENTAR.",
  },
