  // IMAGINI NOI – GALERIE REALĂ ELEMENTAR
  {
    id: "3-color-chess",
    type: "image",
    src: "/images/3-color-cheess.webp",
    category: "Iluzii Optice",
    title: "Șah tridimensional cu trei culori",
    alt: "Joc de șah tridimensional cu trei culori care testează percepția și logica vizuală.",
  },
  {
    id: "catch-it",
    type: "image",
    src: "/images/catch-it.webp",
    category: "Experimente Practice",
    title: "Joc de reacție și coordonare Catch It",
    alt: "Participant testând viteza de reacție și coordonarea la jocul interactiv Catch It.",
  },
  {
    id: "kids-group",
    type: "image",
    src: "/images/grup-din-3-copii.jpg",
    category: "Explorare",
    title: "Copii explorând jocuri educative",
    alt: "Trei copii care colaborează și explorează jocuri educative într-un spațiu ELEMENTAR.",
  },
  {
    id: "cubes",
    type: "image",
    src: "/images/cubes.jpg",
    category: "Experimente Practice",
    title: "Construcții modulare tip cub",
    alt: "Structură modulară construită din cuburi, dezvoltând gândirea spațială.",
  },
  {
    id: "selfie-zone",
    type: "image",
    src: "/images/Elementar-selfie.webp",
    category: "Explorare",
    title: "Zona selfie ELEMENTAR",
    alt: "Platformă selfie iluminată cu logo-ul ELEMENTAR într-o zonă interactivă.",
  },
  {
    id: "human-organs",
    type: "image",
    src: "/images/organe-interne.webp",
    category: "Experimente Practice",
    title: "Model anatomic – corpul uman",
    alt: "Model anatomic educativ cu organele interne ale corpului uman expuse.",
  },
  {
    id: "pentagon-illusion",
    type: "image",
    src: "/images/pentagon.webp",
    category: "Iluzii Optice",
    title: "Iluzie optică geometrică infinită",
    alt: "Structură geometrică tip pentagon cu efect de iluzie optică infinită.",
  },
  {
    id: "real-vs-copy",
    type: "image",
    src: "/images/real-and-copy.webp",
    category: "Iluzii Optice",
    title: "Real vs reflexie",
    alt: "Instalație de percepție vizuală care compară obiectul real cu reflexia sa.",
  },
